### PR TITLE
Fix bug "Internal error: unable to find the outer accessor symbol of class"

### PR DESCRIPTION
**Pull request by DmytroMitin**
See details: https://stackoverflow.com/questions/64950654/how-to-use-a-universe-tree-created-and-type-checked-in-one-scala-macro-executi

### CODE REVIEW

**Comment by readren** [comment]
First of all, thank you a lot for all your help. 
Regarding this pull request, I don't understand what is the benefit. The change you suggest is sharing an unchecked duplicate, which is what the `master` already is doing.
The only addition is the duplication of the `Tree` before type-checking. Do you think it is necessary? Does the `typecheck` method mutate its argument? Applying `showRaw` to the argument before and after the checkout does not reveal any difference.
Perhaps I am missing something.

**Comment by DmytroMitin** [comment]
@readren Maybe you're right. I was focused on fixing compilation and haven't noticed that after it's fixed there are no longer benefits. So it seems your idea to speed up compilation with sharing typed trees among macro expansions generally doesn't work.

Regarding duplication. It's hard to say whether it's strictly necessary. It's possible that you do not get into cases where it's necessary. But yes, generally I guess `c.typecheck` can mutate its argument (although I'm not ready to show en example right now).

**Comment by readren** [comment]
@DmytroMitin _"So it seems your idea to speed up compilation with sharing typed trees among macro expansions generally doesn't work."_ 
Unfortunately not. And the bad consequence of that is not only the extra processing time required to type-check the same `Tree` instance more than one time, but also the re-execution of all the implicit macros triggered by said type-check.
Perhaps there is possible to keep the implicit search results of the type-checked `Tree` to, at least, avoid the re-execution of the implicit macros, which not only take time but also flood the log.

**Comment by DmytroMitin** [comment]
@readren Look at `shapeless.cachedImplicit` and `shapeless.Cached`
https://github.com/milessabin/shapeless/blob/master/core/src/main/scala/shapeless/package.scala#L111
https://github.com/milessabin/shapeless/blob/master/core/src/main/scala/shapeless/cached.scala
https://github.com/milessabin/shapeless/blob/master/core/src/test/scala/shapeless/cached.scala
https://stackoverflow.com/questions/54411094/caching-the-circe-implicitly-resolved-encoder-decoder-instances
https://github.com/milessabin/shapeless/blob/master/core/src/test/scala/shapeless/implicits.scala

**Comment by DmytroMitin** [comment]
@readren Still not an example, just a couple of quotes regarding `c.typecheck`
> Don't forget to duplicate that tree before typechecking, because c.typeCheck mutates the tree in place, which might be undesireable.

https://stackoverflow.com/questions/27965857/obtaining-a-weaktypetag-for-a-given-type-in-a-scala-macro-annotation
https://stackoverflow.com/questions/19379436/cant-access-parents-members-while-dealing-with-macro-annotations

**Comment by readren** [comment]
Thank you again. I will add the duplication in the next commit.

**Comment by readren** [comment]
@DmytroMitin Regarding the mutation of the argument of the `typecheck` method, perhaps that was true before, with the deprecated `typeCheck` (with uppercase C). Who knows?

**Comment by DmytroMitin** [comment]
@readren Maybe you're right. `c.typecheck` is [implemented](https://github.com/scala/scala/blob/2.13.x/src/compiler/scala/reflect/macros/contexts/Typers.scala#L32-L52) in `scala.reflect.macros.contexts.Typers` and seems to do duplication
```scala
...
callsiteTyper.silent(_.typed(universe.duplicateAndKeepPositions(wrapped), mode, pt) ...
```

**Comment by DmytroMitin** [comment]
@readren It's funny that (on contrary to macros) runtime-reflection Toolbox [doesn't](https://github.com/scala/scala/blob/2.13.x/src/compiler/scala/tools/reflect/ToolBoxFactory.scala#L184-L197) make duplication :)
```scala
currentTyper.silent(_.typed(expr, mode, pt) ...
```

**Pull request closed without merging**
